version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis-service
    ports:
      - "6379:6379"
    restart: always

  mongo:
    image: mongo:latest
    container_name: my-mongo-service
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: always

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    restart: always

  app:
    build: .
    container_name: python-app
    depends_on:
      - redis
      - mongo
      - neo4j
    environment:
      - MONGO_URI=mongodb://root:example@my-mongo-service:27017/
      - REDIS_HOST=my-redis-service
      - REDIS_PORT=6379
    volumes:
      - .:/app
    command: ["python", "mongo_setup.py"]
    restart: always

volumes:
  mongo_data:
  neo4j_data:
